simulink_to_graphml('graphml_test_cases', 'graphml_test_cases/with_comments', 'commented.graphml')
simulink_to_graphml('graphml_test_cases', 'graphml_test_cases/non_input_drivers', 'non_input_drivers.graphml')
simulink_to_graphml('graphml_test_cases', 'graphml_test_cases/nested_enabled_subsystem', 'enabled.graphml')
simulink_to_graphml('graphml_test_cases', 'graphml_test_cases/nested_subsystem', 'nested.graphml')
simulink_to_graphml('graphml_test_cases', 'graphml_test_cases/simple_subsystem', 'simple.graphml')