language: cpp

addons:
  apt:
    packages:
    - cmake
    - libxerces-c-dev

compiler:
  - clang
  - gcc

script:
  - mkdir build && cd build
  - cmake ..
  - make

notifications:
  slack:
    secure: oLeqPA3FdMiJ6Klktr35fUdxO/INyG0azaTPiI0ZvyzmyqrGI21ed55jCPzyd2OM/xIiFEGxYPFjEf7gBcDqdcUIjZzIXJFa1u4/eW+REnT1sLJ5NehZrZViOmH2+O/icsdjS7jbYPGkUjBMMODEdRND8d/xO62F34yeRV06UE2AYJr3Rzd9u8e7eZNEIpMtoCQcpkUx+Vg8xXQQclbbwkmAuM309uDOBoI/6CGA6VJUp8/f3YvlnY/zdJp8i9xQo+vElDAD/KhsdsLluRei1zBstyStA1NEXYmFXI2k2BYRPDS2PSQjNEQWaX0AYPpLmZ3JPfqEdqPcOfR4lNhODtVz1T1DuyigGk+/tIF9fQbTHTSpQzRtQ3lCBtJlqSnWYhr1LO6DDxBjIP5h9aJ0aaFSopw0oLik0PmQ/zf4TB7jqNyJdJ3Iq2DQN9svd4ZDCzEE5QlhXC8D5CIIZGuwEo5Plxm8feRcx4RcaysT2QICLQeVmwHWWfippt3k9+e2iBWrzBvyk4X21fVfceaO+jirlo2ET/DdMuYUU3VWxRUPF2ysNJ3Wi4A7j0AVUBhapfQ+MZOjB2qzyEjXdryaXKJ3lbSlKElbPH9iUBW4xGtzt60B7dLsa+zJbmsVjH6G8HDRdLMvEScYLIO49R9c8l2f/Yi7VBFrCLQDzStBNvw=
    on_success: always