language: cpp
version: ~> 1.0

#Using trick from https://genbattle.bitbucket.io/blog/2016/01/17/c++-travis-ci/
# https://github.com/travis-ci/travis-ci/issues/6300
# https://github.com/travis-ci/travis-ci/issues/7100

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew unlink python@2; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew bundle -v; fi

before_script:
    - if [[ "$COMPILER" = "g++-5"        ]] && [[ "$TRAVIS_OS_NAME" != "osx" ]]; then export CXX="g++-5" CC="gcc-5";              fi
    - if [[ "$COMPILER" = "clang++-3.8"  ]] && [[ "$TRAVIS_OS_NAME" != "osx" ]]; then export CXX="clang++-3.8" CC="clang-3.8";    fi

jobs:
  include:
    - compiler: gcc
      os: linux
      dist: trusty
      env: COMPILER=g++-5
    - compiler: clang
      os: linux
      dist: trusty
      env: COMPILER=clang++-3.8
#    - compiler: gcc
#      os: osx
#      osx_image: xcode9.4
#      env: COMPILER=g++
    - compiler: clang
      os: osx
      osx_image: xcode9.4
      env: COMPILER=clang++

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
#    - llvm-toolchain-trusty-3.8
    packages:
    - cmake
    - libxerces-c-dev
    - clang-3.8
    - gcc-5
    - g++-5
    - graphviz
    - doxygen

script:
  - echo $CXX; echo $CC
  - mkdir build && cd build
  - cmake ..
  - make
  - make test ARGS="-V"

notifications:
  slack:
    secure: h5AYGVV90kulQHihxIrR1Adf78PXL7V+UIDdn8Ts/vpmV972bONud9XXkTZGVz/Dv6GqmLYXHRVaaFfex3dB5kJwn4rWtpR3nyAFF606ZRgIIucph+vd/xWCexf8vwYzmEQ5zZ3J0Ixw/LLVB+Yk/wShcIlupr4escnfmfMEPkynR90Dgs18mMWGa1iep4eeayFrGrj4FHIloGyifoYHBqpAyCJgsfw5IuUVfDXuFBOH67AUCLmn7hqp+7xDHEz4CkX8EduM6HndG5TLDOZgxHqoGQ67nU86pyB9pg7TgxfbZlVJ7Sc9W8eC//Gv0b0BspLQefe0rTCSl2FEuz7Y6160tAzL4s3EabFxDcU3IC0T9U4WVvSfLsv94EftsUnhgvTu/ggr2uzACT5FsyabRfgt0ZHZvg5ypeBwkOzKOCgVFLo1HqBRze/4GfAs1e9RsEp+lxjkwWbl5+rwvcLbs1aiM9PJ/pBJq3lQhmAq3wvyLkvyOT5r+Y17hHqvl3p+PrkGvYaHs5jLrykN1hCYqY96KOLELHMyj/ugSWQoPmUUUS8zhOY8byOBORcykGe/0ErZWAeVXrLaJ+IGKvQUw74HQSnicSGmTdVHFqZhHYAaGVsViRrSP7xncDAG1G16nw3XGNqs+5IJQw6L9gBRlSUKU7o4lp0uBq2PgpbEf9M=
