language: cpp

#Using trick from https://genbattle.bitbucket.io/blog/2016/01/17/c++-travis-ci/
# https://github.com/travis-ci/travis-ci/issues/6300
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install xerces-c; fi

os:
  - linux
  compiler:
    - clang
    env: COMPILER=clang++-3.6
    - gcc
    env: COMPILER=g++-5
  - osx
  compiler:
      - clang
      - gcc

dist: trusty
osx_image: xcode9.4

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-trusty-3.6
    packages:
    - cmake
    - libxerces-c-dev
    - clang-3.6
    - gcc-5
    - g++-5

compiler:
  - clang
  - gcc

script:
  - mkdir build && cd build
  - cmake ..
  - make
  - make test ARGS="-V"

notifications:
  slack:
    secure: h5AYGVV90kulQHihxIrR1Adf78PXL7V+UIDdn8Ts/vpmV972bONud9XXkTZGVz/Dv6GqmLYXHRVaaFfex3dB5kJwn4rWtpR3nyAFF606ZRgIIucph+vd/xWCexf8vwYzmEQ5zZ3J0Ixw/LLVB+Yk/wShcIlupr4escnfmfMEPkynR90Dgs18mMWGa1iep4eeayFrGrj4FHIloGyifoYHBqpAyCJgsfw5IuUVfDXuFBOH67AUCLmn7hqp+7xDHEz4CkX8EduM6HndG5TLDOZgxHqoGQ67nU86pyB9pg7TgxfbZlVJ7Sc9W8eC//Gv0b0BspLQefe0rTCSl2FEuz7Y6160tAzL4s3EabFxDcU3IC0T9U4WVvSfLsv94EftsUnhgvTu/ggr2uzACT5FsyabRfgt0ZHZvg5ypeBwkOzKOCgVFLo1HqBRze/4GfAs1e9RsEp+lxjkwWbl5+rwvcLbs1aiM9PJ/pBJq3lQhmAq3wvyLkvyOT5r+Y17hHqvl3p+PrkGvYaHs5jLrykN1hCYqY96KOLELHMyj/ugSWQoPmUUUS8zhOY8byOBORcykGe/0ErZWAeVXrLaJ+IGKvQUw74HQSnicSGmTdVHFqZhHYAaGVsViRrSP7xncDAG1G16nw3XGNqs+5IJQw6L9gBRlSUKU7o4lp0uBq2PgpbEf9M=
