language: cpp

addons:
  apt:
    packages:
    - cmake
    - libxerces-c-dev

compiler:
  - clang
  - gcc

script:
  - mkdir build && cd build
  - cmake ..
  - make

notifications:
  slack:
    secure: "LqQHnf9axMfxNjgiNW01VsbYLsA5zpE9a9oRvd9clj//+yQLX/y1HYBCj8bf2UrvOBpTk/55R+U9B/iJGZVYYQZ0C6+neLD+stwubgbMa4DEUf0p1MTScLw6+NTX4ZWEkMKBZw10lJh3exH9uQ+1jTXfsUUkbN7joevOu9YspjgH7Aducx4ssufHXmEKvlHKIivDfBq7/57Q+ZKmfo7Gh7ki87js6/kg4FL34f91ksHgxaUbCUH7SI0Sy3jB/mNpJm3EGES75yCakoEI1CqDpthsY1lp2JkkiWmmsC70obiZVN3cNiIotzjihSzsGL6IiqsALi1R5xC9J6aCf1X2SIG+lBWVjHa+IvniV/WgwoFH7Fp6EWONoNAU9ygknYtvT+bjJxbVnk8fwoejZU79sXXqKJOS+xARqJ/DHSbK6o+UpFgwlKFjk1yjFTQYYT2QPNecJUchKqoMjw7Ci7FzyhCJQEyEMjBh4322zOdftinYi2kYeFWz2+vUUAxqwUZvwn2SFzNQ/uI/R6B4NfGZUY8CAXE0vnrLfDLTZNm0rZOh75rDvGCXHnGrP4zNpF0xAhjZwDJ8RpEBkRmvYDIEyDPDj2lkklJ3zBiCRj0S0MFr6rnYmkuP/9KuNk8HkT5umRmjhNAEB2XyBnYI9XEi2gdMXTIBQo1zCOnZ9SIuzb0="
    on_success: always