# Get Lines of Code Report

name: Lines of Code

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Install Dependencies
        shell: bash
        run: sudo apt install cloc; sudo apt remove cloc
        
      - name: Clone Cloc (1.9)
        shell: bash
        run: git clone https://github.com/AlDanial/cloc.git ~/cloc && cd ~/cloc && git checkout v1.90
        
      - name: Build and Install CLoc
        shell: bash
        run: cd ~/cloc/Unix. && make && sudo make install

      - name: Lines of Code for Src
        run: cloc --timeout 0 "$GITHUB_WORKSPACE/src" | tee ~/srcLoc.log
        
      - name: Lines of Code for Test
        run: cloc --timeout 0 "$GITHUB_WORKSPACE/test/src" | tee ~/testLoc.log
        
      - name: Lines of Code for Src & Test
        run: cloc --timeout 0 "$GITHUB_WORKSPACE/src" "$GITHUB_WORKSPACE/test/src" | tee ~/srcTestLoc.log

      - name: Upload Loc Reports
        uses: actions/upload-artifact@v2
        with:
          name: locReport
          path: ~/*.log
